### ISSUE TITLE
report an error when player die

### ISSUE THREAD

**Issue by hyi200333** [EndlessCodeGroup/RPGInventory#151] opened 2018-05-09 14:25 UTC
### Prerequisites

* [x] Are you running the latest version?
* [x] Did you check the FAQs on [plugin's page](https://www.spigotmc.org/resources/12498/)?
* [ ] Did you check the [Wiki](http://rpginventory.endlesscode.ru/)?
* [x] Did you configure [config.yml](https://github.com/EndlessCodeGroup/RPGInventory/blob/master/src/main/resources/config.yml)?
* [ ] Did you perform a cursory search?
* [x] Can you reproduce the problem on clean server (with installed only the plugin and dependencies)?

### Description

 ```
Could not pass event PlayerDeathEvent to RPGInventory v2.1.6-PRE
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:412) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:423) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:951) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:577) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.EntityMonster.B(EntityMonster.java:68) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.PathfinderGoalSelector.a(SourceFile:129) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:664) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2090) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:507) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.EntityMonster.n(EntityMonster.java:24) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1939) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.EntityMonster.B_(EntityMonster.java:28) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.EntitySpider.B_(EntitySpider.java:45) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1643) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1613) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
        at ru.endlesscode.rpginventory.utils.ItemUtils.toBukkitItemStack(ItemUtils.java:254) ~[?:?]
        at ru.endlesscode.rpginventory.utils.ItemUtils.getTag(ItemUtils.java:90) ~[?:?]
        at ru.endlesscode.rpginventory.utils.ItemUtils.getTag(ItemUtils.java:84) ~[?:?]
        at ru.endlesscode.rpginventory.item.ItemManager.getCustomItem(ItemManager.java:144) ~[?:?]
        at ru.endlesscode.rpginventory.inventory.InventorySaver.save(InventorySaver.java:60) ~[?:?]
        at ru.endlesscode.rpginventory.event.listener.PlayerListener.onPlayerDead(PlayerListener.java:128) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-aa05e55]
        ... 29 more
```

### Steps to Reproduce

This happens at any player death.

### Environment

**Server Core:** [Spigot]\
**Server Version:** [1.12.1]\
**Plugin Version:** [2.1.6-PRE]

**Comment by OsipXD** [comment] 2018-05-09 15:39
Duplicate of #144

**Closed by OsipXD** 2018-05-09 15:39 UTC
