### ISSUE TITLE
Message that link isn't direct but I think it's direct

### ISSUE THREAD

**Issue by Fargus5** [EndlessCodeGroup/RPGInventory#106] opened 2017-12-28 09:30 UTC
Hi, could you explain to me why I'm receiving this:

```
[08:54:11] [Server thread/WARN]: [RPGInventory] ######### Something wrong with your RP link! #########
[08:54:11] [Server thread/WARN]: [RPGInventory] # Link isn't direct. Redirect found!
[08:54:11] [Server thread/WARN]: [RPGInventory] # Your link: https://www.dropbox.com/s/5y2anxka15xo0ru/HerosFaith.zip?dl=1
[08:54:11] [Server thread/WARN]: [RPGInventory] # Direct link: https://dl.dropboxusercontent.com/content_link/RVTNrAelhCAVmtVg50N7J0JPv42nPKsOWpZ00ouvH7KDKzyB5ZEFsMnEe5yDhnmD/file?dl=1
[08:54:11] [Server thread/WARN]: [RPGInventory] ######################################################
```

My dropbox link is direct I think, the texture have no apparently problems in game

**Comment by OsipXD** [comment] 2017-12-29 13:30
No your link isn't direct if you see this message.
You can ignore this message or just replace your link by given direct link.

**Comment by Fargus5** [comment] 2017-12-29 16:34
I think that there is an error on your code.
The link is direct, it is taken with dropbox
try to open the link and you will see that is a direct link

https://www.dropbox.com/s/5y2anxka15xo0ru/HerosFaith.zip?dl=1

**Comment by OsipXD** [comment] 2017-12-29 16:43
There no error. Check your link here: http://www.redirect-checker.org/index.php

**Comment by Fargus5** [comment] 2017-12-29 16:45
What I have to check? the link works for me and also when I enter into the server the texturepack will be downloaded.. I don't understand sorry

**Comment by OsipXD** [comment] 2017-12-30 05:41
Yes in this case it works fine (may be Minecraft can follow one redirect)

**Comment by Fargus5** [comment] 2017-12-30 09:58
I tried but it give me informations that I don't understand.
I will try to put the file into my website. I will let you know

**Comment by Fargus5** [comment] 2017-12-30 10:05
https://www.herosfaith.eu/theme/mctexture/HerosFaith.zip

**Comment by OsipXD** [comment] 2017-12-30 15:13
Why you not use https://dl.dropboxusercontent.com/content_link/RVTNrAelhCAVmtVg50N7J0JPv42nPKsOWpZ00ouvH7KDKzyB5ZEFsMnEe5yDhnmD/file?dl=1
?

**Comment by KnifeKat** [comment] 2018-01-01 11:54
Fargus. I helped @Lezarath do this on the Discord, his works, as well as mine. I can delete my Force-Resource Pack Link, and redo it, over and over and over again. 

There is absolutely nothing wrong with his code. 

Also, I doubt you verified the SHA-1 is correct. 

If you *did* somehow make sure it was correct, you have no clue on how Dropbox works and Direct Links. You can't just "Copy Link", and expect that to work. That is -NOT- a Direct Link in Dropbox. Its a SourceLink that ONLY you, the owner of the dropbox can use to access the item in the box through a browser or another. It is NOT meant for use through a program(Minecraft) or outsourced Site(Trying to download it through another program).

I will not discuss how it works here, as I have made a guide that is huge, and even toddlers can understand it(hopefully). So you'll have to wait till the Guide is out. Once I have the new Overview page finished, you'll be able to follow it. If you somehow mess up that guide, then there will be no way to help you outside of it. As it has detailed click-for-click pictures demonstrating how to handle this feature of the plugin.

In regard to this, this is working as intended. I've verified it several times.

This issue can be closed. Thank you.

**Comment by Fargus5** [comment] 2018-01-01 11:58
@KnifeKat yes I verified man :)

https://www.herosfaith.eu/themes/mctexture/HerosFaith.zip this was the link and the sha was correct.
You can test by yourself the links that I posted up. Nothing to explain to the evidence. Anyway for me there is no problem, I reput the dropbox link. Both are directs but the system consider them as not

**Comment by KnifeKat** [comment] 2018-01-01 12:03
I am not going to argue this with you, when the feature works for me and for 5+ others I've helped in the Discord. 

*You have no concept on how Dropbox works.* You can *NOT* simply copy the link. *Like I said before.* You *HAVE* to use *ANOTHER METHOD* ... *Like I said.* 

If you are using a Direct Link, and know for 100% correct that the Direct Link is indeed *correct*. Then your SHA-1 is *not* correct. End of story. In this case, if you're using Dropbox, and post the link here, I can tell you immediately rather that link is Direct or not. Just by looking at it.

What method are you using to find the SHA-1. This is another issue. 

Once the Guide is out, you can follow that guide. Arguing here that we are in the wrong, when it is you having the user error, will not turn out in your favor. You might as well wait for the guide that will be released next week, or insist that your details are correct.

If you want the guide ahead of time, you can ask a member of the discord that I've PMed the guide to, to enlighten you with the guide. I'll not be releasing the guide publicly otherwise until the whole new overview page is finished.

Thank you in advance.

**Comment by Fargus5** [comment] 2018-01-01 12:05
Works also for me, so I don't understand what is wrong with you.... Did you read up?

**Comment by KnifeKat** [comment] 2018-01-01 12:14
Then if this feature works for you, why are you making an issue stating its not working for you/errors in the console about it?

Doesn't make any sense. If the Dropbox works, then use it. If you're incorrectly using the .eu link, then avoid it. Use what works for you.

.eu link works perfectly for me after I have used it in the past 5 minutes. So, I do not see an issue here.

Issue is closed, then.

**Comment by Fargus5** [comment] 2018-01-01 12:17
If you read up, I reported that it works but I'm just receiving the notification. The developer has already answered. He already knows. So I still doesn't understand. Who are you? You are haveing the same problem or you want just to spam in this conversation?

**Comment by OsipXD** [comment] 2018-01-01 17:28
@Fargus5, technically link isn't direct but if it works fine, you free to use it. Just ignore this message.

**Closed by OsipXD** 2018-01-01 17:28 UTC
Labels: type: question
